version: '3.8'

services:
  postgres:
    container_name: todos_postgres
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5434:5432'
    networks:
      - todos-network
    restart: unless-stopped

  pgadmin:
    container_name: todos_pgadmin
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5052:80'
    networks:
      - todos-network
    restart: unless-stopped
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: todos_nodejs_image
    container_name: todos_nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - todos-network
networks:
  todos-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
